### ISSUE TITLE
design doc v2

### ISSUE THREAD

**Issue by hashsequence** [hashsequence/Linux-Job-Worker#3]
### TODO
- [x] Revisit Api Implementation, splitting up Execute Api's to simplify rpc, incorporate a different designing in assigning a unique id to job requests 

- [x] Elaborate More on Encryption and Authentication choice (Mutual Tls)

- [x] Revisit Design of DataStore 
    - will store the following for every job in server in in-memory table:
    ```go
            pid int
            string startTimeStamp
            string endTimeStamp
            string processName
            string uuid
            string logPath
            bool isRunning
            int exitCode
    ```
- [x] Revisit using logs for output
   - I think i would be outputing stdout and stderr to physical logs
